spring:
  datasource:
    url: jdbc:h2:file:./h2data/user_manager;DB_CLOSE_DELAY=-1
    username: root
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type: trace



cors-policies: http://localhost:4200, http://127.0.0.1:4200